# For binary mask & instance contour prediction.
# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/config.py

SYSTEM:
  NUM_GPUS: 4
  NUM_CPUS: 16
MODEL:
  ARCHITECTURE: 'unetr3d_transformer_csa' # 
  FILTERS: [28, 36, 48, 64, 80]
  INPUT_SIZE: [32, 256, 256]  
  OUTPUT_SIZE: [32, 256, 256]  
  OUT_PLANES: 2
  LOSS_OPTION: [['DiceLoss', 'WeightedBCE'], ['DiceLoss', 'WeightedBCE']]
  LOSS_WEIGHT: [[0, 1], [0, 1]]
#  LOSS_OPTION: [['WeightedBCE'], ['WeightedBCE']]
#  LOSS_WEIGHT: [[1], [1]]
  TARGET_OPT: ['0','4-2-1'] # Multi-task learning: binary mask, instance segmentation
  WEIGHT_OPT: [['1'],['1']]
DATASET:
  IMAGE_NAME: 'configs/MitoEM/im_train_640_0329.json'  # configs/MitoEM/im_train_640_0329.json
  LABEL_NAME: 'configs/MitoEM/gt_train_640_0329.json'
  INPUT_PATH: '/data/local/disk1/sjwlab/chenzx/code/ssEM_seg/' # work container /data/local/disk1/sjwlab/chenzx/code/ssEM_seg
  # inference: save model
  INFERENCE_PATH: '/data/local/disk1/sjwlab/chenzx/code/ssEM_seg/'
  OUTPUT_PATH: 'outputs/dataset_output_unet_res_ca_without_pp/'
  PAD_SIZE: [0, 0, 0] #
  DO_CHUNK_TITLE: 1 # 
  DATA_CHUNK_NUM: [1, 1, 1] # 
  DATA_CHUNK_ITER: 2500 # 
  LABEL_EROSION: 1
  USE_LABEL_SMOOTH: False
  LABEL_SMOOTH: 0.1

SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 1e-04
  ITERATION_STEP: 1 
  ITERATION_SAVE: 1500  # save model
  ITERATION_TOTAL: 200000 # total iterationv 200000
  SAMPLES_PER_BATCH: 1 
INFERENCE:
  INPUT_SIZE: [32, 256, 256]  # [16, 128, 128]
  OUTPUT_SIZE: [32, 256, 256] # [16, 128, 128]
  IMAGE_NAME: 'configs/MitoEM/im_test_0614.json'  # m configs/MitoEM/im_test_1024.json    configs/MitoEM/im_test_640_0329.json  /data/local/disk1/sjwlab/chenzx/code/ssEM_seg/configs/MitoEM/im_test_crop2_1202.json
  OUTPUT_PATH: 'outputs/inference_output/'
  OUTPUT_NAME: 'result.h5'
  PAD_SIZE:  [16, 128, 128]  
  AUG_MODE: 'mean'
  AUG_NUM: 0
  STRIDE: [1, 128, 128] 
  SAMPLES_PER_BATCH: 12
